"""
Persistent cookie storage.

Cookies are session credentials: this module writes them with restrictive
permissions, replaces the jar atomically so a crash cannot destroy a good one,
and never logs a cookie value.
"""

from __future__ import annotations

import contextlib
import json
import os
import tempfile
import threading
from collections.abc import Mapping
from pathlib import Path
from typing import Literal

from curlx.utils import get_logger

logger = get_logger("curlx.cookies")

_FILE_MODE = 0o600

_NETSCAPE_HEADER_LINES = (
    "# Netscape HTTP Cookie File",
    "# https://curl.se/docs/http-cookies.html",
    "# Generated by curlx. Do not edit while a client is running.",
    "",
)

# curl prefixes the domain field with this marker for HttpOnly cookies; the
# resulting line looks like a comment but is not one.
_HTTPONLY_PREFIX = "#HttpOnly_"

# Reserved TLD (RFC 2606) - a domain that can never resolve, so a jar written
# from the flat mapping API cannot be mistaken for one scoped to a real site.
_PLACEHOLDER_DOMAIN = "unknown.invalid"
_PLACEHOLDER_PATH = "/"

_NETSCAPE_FIELD_COUNT = 7
_NAME_FIELD = 5
_VALUE_FIELD = 6


class CookieJar:
    """
    A file-backed jar of ``name -> value`` cookies.

    Two on-disk formats are supported:

    ``json``
        A flat JSON object. Lossless for this API and the sensible default.

    ``netscape``
        The tab-separated ``# Netscape HTTP Cookie File`` layout that curl and
        wget read and write (``domain``, ``flag``, ``path``, ``secure``,
        ``expiry``, ``name``, ``value``).

        **Known limitation.** This class models a cookie as a bare name/value
        pair, so the four attribute columns cannot be reconstructed on write.
        They are filled with placeholders: domain ``unknown.invalid``, path
        ``/``, secure ``FALSE``, expiry ``0`` (session cookie). Such a file is
        structurally valid and round-trips through :meth:`load`, but curl will
        not send those cookies to any real host, because their domain matches
        nothing. Use this format to *read* a jar produced by curl - that
        direction is exact - and prefer ``json`` for storage curlx owns.

    Reading never raises: a missing, unreadable, or corrupt file yields ``{}``
    and a warning, so a damaged jar degrades to a logged-out session instead of
    crashing the client at startup.

    Example:
        >>> jar = CookieJar("~/.cache/curlx/session.json")  # doctest: +SKIP
        >>> jar.save({"session_id": "abc123"})              # doctest: +SKIP
        >>> jar.load()                                       # doctest: +SKIP
        {'session_id': 'abc123'}
    """

    def __init__(self, path: str | Path, *, fmt: Literal["json", "netscape"] = "json") -> None:
        """
        Args:
            path: Jar location. ``~`` is expanded. Parent directories are
                created by :meth:`save`, not here - constructing a jar has no
                filesystem side effects.
            fmt: On-disk format, ``"json"`` or ``"netscape"``.

        Raises:
            ValueError: If ``fmt`` is not a recognised format.
        """
        if fmt not in ("json", "netscape"):
            raise ValueError(f"Unknown cookie format: {fmt!r} (expected 'json' or 'netscape')")

        self.path = Path(path).expanduser()
        self.fmt = fmt
        self._cookies: dict[str, str] = {}
        self._lock = threading.Lock()

    def load(self) -> dict[str, str]:
        """
        Read the jar from disk and return a copy of its contents.

        Returns:
            The stored cookies, or ``{}`` if the file is missing, unreadable, or
            unparseable. Never raises; failures are logged without any cookie
            value or file content.
        """
        try:
            raw = self.path.read_text(encoding="utf-8")
        except FileNotFoundError:
            return self._replace({})
        except OSError as exc:
            logger.warning(
                "Cookie jar unreadable, starting empty | path=%s | error=%s",
                self.path,
                type(exc).__name__,
            )
            return self._replace({})

        try:
            if self.fmt == "json":
                cookies = self._parse_json(raw)
            else:
                cookies = self._parse_netscape(raw)
        except Exception as exc:
            # Broad by design: a bad jar must degrade to a logged-out session,
            # never break client startup with an unforeseen parser error.
            # Deliberately no line/offset detail: those messages quote the
            # offending file content, which is exactly the secret we hold.
            logger.warning(
                "Cookie jar corrupt, starting empty | path=%s | fmt=%s | error=%s",
                self.path,
                self.fmt,
                type(exc).__name__,
            )
            return self._replace({})

        logger.debug("Cookie jar loaded | path=%s | count=%d", self.path, len(cookies))
        return self._replace(cookies)

    def save(self, cookies: Mapping[str, str]) -> None:
        """
        Write ``cookies`` to disk, replacing any previous contents.

        The write is atomic: the payload lands in a temporary file in the same
        directory, is flushed to stable storage, and is then moved into place
        with :func:`os.replace`. A crash part-way through leaves the previous
        jar intact.

        Args:
            cookies: The full cookie set to persist. Keys and values are
                coerced with ``str``.

        Raises:
            ValueError: In ``netscape`` format only, if a name or value
                contains a tab or newline - those bytes are the record and
                field separators and cannot be represented.
            OSError: If the directory cannot be created or the file cannot be
                written.
        """
        snapshot = {str(name): str(value) for name, value in cookies.items()}
        payload = (
            self._render_json(snapshot) if self.fmt == "json" else self._render_netscape(snapshot)
        )

        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._atomic_write(payload)
        self._replace(snapshot)
        logger.debug("Cookie jar saved | path=%s | count=%d", self.path, len(snapshot))

    def clear(self) -> None:
        """
        Forget every cookie and delete the backing file.

        Deleting a jar that is already gone is a no-op. Any other failure
        propagates: reporting success while credentials remain on disk would be
        worse than the exception.
        """
        self._replace({})
        self.path.unlink(missing_ok=True)
        logger.debug("Cookie jar cleared | path=%s", self.path)

    def __len__(self) -> int:
        """Number of cookies currently held in memory."""
        with self._lock:
            return len(self._cookies)

    def __repr__(self) -> str:
        return f"CookieJar(path={str(self.path)!r}, fmt={self.fmt!r}, count={len(self)})"

    def _replace(self, cookies: dict[str, str]) -> dict[str, str]:
        """Swap the in-memory view and hand the caller its own copy."""
        with self._lock:
            self._cookies = cookies
        return dict(cookies)

    def _atomic_write(self, payload: str) -> None:
        fd, tmp_path = tempfile.mkstemp(
            prefix=f".{self.path.name}.",
            suffix=".tmp",
            dir=str(self.path.parent),
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            # mkstemp already creates at 0600; restated so the guarantee does
            # not depend on the platform's default. os.replace keeps this mode.
            os.chmod(tmp_path, _FILE_MODE)
            os.replace(tmp_path, self.path)
        except BaseException:
            # Never litter the cookie directory with half-written jars.
            with contextlib.suppress(OSError):
                os.unlink(tmp_path)
            raise

    @staticmethod
    def _parse_json(raw: str) -> dict[str, str]:
        if not raw.strip():
            return {}
        data = json.loads(raw)
        if not isinstance(data, dict):
            # ValueError, not TypeError: this is malformed file content, not a
            # caller passing the wrong type.
            raise ValueError("top-level JSON value is not an object")
        return {str(name): str(value) for name, value in data.items()}

    @staticmethod
    def _parse_netscape(raw: str) -> dict[str, str]:
        cookies: dict[str, str] = {}
        for line in raw.splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith("#") and not stripped.startswith(_HTTPONLY_PREFIX):
                continue

            fields = line.split("\t")
            if len(fields) < _NETSCAPE_FIELD_COUNT:
                # A single malformed row should not discard a jar full of good
                # ones; curl's own parser skips lines it cannot read.
                continue

            name = fields[_NAME_FIELD]
            if name:
                cookies[name] = fields[_VALUE_FIELD]
        return cookies

    @staticmethod
    def _render_json(cookies: Mapping[str, str]) -> str:
        # Sorted so a jar that did not change produces a byte-identical file.
        ordered = {name: cookies[name] for name in sorted(cookies)}
        return json.dumps(ordered, indent=2, ensure_ascii=False) + "\n"

    @staticmethod
    def _render_netscape(cookies: Mapping[str, str]) -> str:
        lines = list(_NETSCAPE_HEADER_LINES)
        for name in sorted(cookies):
            value = cookies[name]
            if any(char in name or char in value for char in "\t\r\n"):
                # Names only in the message - the value is the credential.
                raise ValueError(
                    f"Cookie {name!r} cannot be written in netscape format: "
                    "names and values must not contain tabs or newlines"
                )
            fields = (
                _PLACEHOLDER_DOMAIN,
                "FALSE",  # domain does not start with a dot
                _PLACEHOLDER_PATH,
                "FALSE",  # not secure-only
                "0",  # session cookie: no known expiry
                name,
                value,
            )
            lines.append("\t".join(fields))
        return "\n".join(lines) + "\n"
